modLoader = "javafml"
loaderVersion = "[35,)"
source="https://github.com/samolego/forgified-sgui"
issueTrackerURL = "https://github.com/samolego/forgified-sgui/issues"
license = "LGPL-3.0"

[[mods]]
modId = "sgui"
version = "${version}"
displayName = "Server GUI lib"
authors = "patbox"
contributors="aws404, samo_lego"
description = '''
Library for creating server side guis!
Note: this is a port of the fabric sgui by Patbox.
'''
logoFile = "icon.png"

[[dependencies.sgui]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sgui]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
